name: Build OverBind PKGBUILD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
      - name: Update system and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git rust nodejs npm yarn gtk3 webkit2gtk libayatana-appindicator

      - name: Create non-root user and build directory
        run: |
          useradd -m builder
          mkdir -p /home/builder/build
          chown -R builder:builder /home/builder

      - name: Download PKGBUILD
        run: |
          curl -Lo /home/builder/build/PKGBUILD https://raw.githubusercontent.com/Twig6943/OverBind/refs/heads/master/PKGBUILD
          chown builder:builder /home/builder/build/PKGBUILD

      - name: Build package as builder user
        run: |
          runuser -u builder -- bash -c "cd /home/builder/build && makepkg --noconfirm --syncdeps --clean"
