name: Build OverBind PKGBUILD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build PKGBUILD on Arch Linux
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
      - name: Install base-devel and dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git rust nodejs npm yarn gtk3 webkit2gtk libayatana-appindicator

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder .

      - name: Fetch PKGBUILD
        run: |
          mkdir -p /home/builder/build
          cd /home/builder/build
          curl -LO https://raw.githubusercontent.com/Twig6943/OverBind/refs/heads/master/PKGBUILD
        shell: bash

      - name: Build package
        run: |
          cd /home/builder/build
          sudo -u builder makepkg -si --noconfirm
        shell: bash
