jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: Setup user and build dir
        run: |
          useradd -m builder
          mkdir -p /home/builder/build
          chown -R builder:builder /home/builder

      - name: Download PKGBUILD
        run: |
          curl -Lo /home/builder/build/PKGBUILD https://raw.githubusercontent.com/Twig6943/OverBind/refs/heads/master/PKGBUILD
          chown builder:builder /home/builder/build/PKGBUILD

      - name: Build package as builder user
        run: |
          runuser -u builder -- bash -c "cd /home/builder/build && makepkg --noconfirm --syncdeps --clean"
