name: Build OverBind PKGBUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
      - name: Update system and install dependencies
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm
          pacman -S --noconfirm git rust nodejs npm yarn gtk3 webkit2gtk libayatana-appindicator base-devel

      - name: Create builder user and install tauri-cli
        run: |
          useradd -m builder
          #runuser -u builder -- bash -c "source /etc/profile; cargo install tauri-cli"

      - name: Prepare build directory
        run: |
          mkdir -p /home/builder/build
          chown -R builder:builder /home/builder

      - name: Download PKGBUILD
        run: |
          git clone https://github.com/Twig6943/OverBind.git /home/builder/build
          chown -R builder:builder /home/builder/build
          cd /home/builder/build

          # Library fixes
          ln -sf /usr/lib/pkgconfig/javascriptcoregtk-4.0.pc /usr/lib/pkgconfig/javascriptcoregtk-4.1.pc
          ln -sf /usr/lib/pkgconfig/webkit2gtk-4.0.pc /usr/lib/pkgconfig/webkit2gtk-4.1.pc
          
          runuser -u builder -- bash -c "cd /home/builder/build && yarn add -D @tauri-apps/cli && yarn install"
          #curl -Lo /home/builder/build/PKGBUILD https://raw.githubusercontent.com/Twig6943/OverBind/refs/heads/master/PKGBUILD
          #chown builder:builder /home/builder/build/PKGBUILD       

      - name: Build package as builder user
        run: |
          runuser -u builder -- bash -c "export PKG_CONFIG_PATH=/usr/lib/pkgconfig:\$PKG_CONFIG_PATH && export PATH=\$HOME/.cargo/bin:\$PATH && cd /home/builder/build/arch/ && makepkg --noconfirm --syncdeps --clean"

